components: 
  schemas: 
    ApiResponse: 
      type: object
      properties: 
        date: 
          format: date
          type: string
        code: 
          format: int32
          type: integer
        message: 
          type: string
  securitySchemes: 
    Authorization: 
      in: header
      name: Authorization
      type: apiKey
    "api-key": 
      in: header
      name: "api-key"
      type: apiKey
    "api-id": 
      in: header
      name: "api-id"
      type: apiKey
    token: 
      in: header
      name: token
      type: apiKey
servers: 
  - url: "http\x3A//20.87.213.78\x3A8080/jw/api"
openapi: "3.0.1"
paths: 
  "/formcreator/formcreator/forms": 
    post: 
      summary: "Create\x20a\x20new\x20form\x20from\x20JSON\x20definition\x20or\x20file\x20upload"
      security: 
        - "api-key": 
          "api-id": 
        - "api-key": 
          "api-id": 
          token: 
        - Authorization: 
          "api-key": 
          "api-id": 
      requestBody: 
        content: 
          "application/json": 
      description: "Creates\x20a\x20Joget\x20form\x20based\x20on\x20provided\x20JSON\x20definition\x20and\x20metadata.\x20Supports\x20both\x20JSON\x20\x28application/json\x29\x20and\x20file\x20upload\x20\x28multipart/form-data\x29.\x20Optionally\x20creates\x20API\x20endpoint\x20and\x20CRUD\x20interface.\x20Requires\x20formId\x2C\x20formName\x2C\x20tableName\x2C\x20and\x20formDefinition\x20\x28or\x20formDefinitionFile\x29."
      operationId: createForm
      responses: 
        200: 
          description: "Form\x20created\x20successfully"
          content: 
            "application/json": 
        400: 
          description: "Invalid\x20request\x20-\x20validation\x20failed"
          content: 
            "application/json": 
        500: 
          description: "Server\x20error\x20during\x20form\x20creation"
          content: 
            "application/json": 
      parameters: 
        - schema: 
            type: string
          in: query
          name: appId
          required: false
        - schema: 
            type: string
          in: query
          name: appVersion
          required: false
        - schema: 
            xml: 
              name: HttpServletRequest
            type: object
            properties: 
          in: query
          name: request
          required: false
      tags: 
        - formcreator
info: 
  description: ""
  title: formCreatorApi
  version: "9.0.4"
tags: 
  - name: formcreator
    description: ""